name: GitHub Actions Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:  
  Build-MTApiService:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1
      - name: Restore nuget packages
        run: nuget restore MetaTraderApi_2017.sln
      - run: echo "🖥️ The workflow will now start building the MTApiService.dll"
      - name: Build project for release
        run: msbuild MTApiService\MTApiService.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  Build-MtApiServiceNetCore:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1
      - name: Restore nuget packages
        run: nuget restore MetaTraderApi_2017.sln
      - run: echo "🖥️ The workflow will now start building the MtApiServiceNetCore.dll"
      - name: Build project for release
        run: msbuild MtApiServiceNetCore\MtApiServiceNetCore.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - run: echo "🍏 This job's status is ${{ job.status }}."
