name: GitHub Actions Build
run-name: Building & uploading projects
on: [push]
jobs:
  Build-Solution:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '5.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore nuget packages
        run: nuget restore MetaTraderApi_2017.sln
      - run: echo "🖥️ The workflow will now start building the MTApiService.dll"
      - name: Build MTApiService for release
        run: msbuild MTApiService\MTApiService.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Build MtApi5 for release
        run: dotnet build MtApi5\MtApi5.csproj -c Release
      - name: Build MT5Connector for release
        run: msbuild MT5Connector\MT5Connector.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release        
      - name: Build Installer for release
        run: msbuild MtApi5Installer\MtApi5Installer.wixproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Prepair target file structure
        run: |
          mkdir ${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable
          mkdir ${GITHUB_WORKSPACE}\a\mtapi\mtapi\client
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MTApiService.dll" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MTApiService.dll"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MT5Connector.dll" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Libraries\MTApiService.dll"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MT5Connector.lib" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Libraries\MT5Connector.lib"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MT5Connector.exp" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Libraries\MT5Connector.exp"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\mq5\MtApi5.ex5" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Experts\MtApi5.ex5"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\mq5\MtApi5.mq5" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Experts\MtApi5.mq5"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\mq5\hash.mqh" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Include\hash.mqh"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\mq5\json.mqh" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\portable\MQL5\Include\json.mqh"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MtApi5.dll" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\client\MtApi5.dll"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\products\Release\MtApiServiceNetCore.dll" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\client\MtApiServiceNetCore.dll"
          move "${GITHUB_WORKSPACE}\a\mtapi\mtapi\build\installers\Release\MtApi5Installer_x86.msi" "${GITHUB_WORKSPACE}\a\mtapi\mtapi\MtApi5Installer_x86.msi"
      - name: PR artifacts
        uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/master'
        with:
          name: MetaTraderApi
          retention-days: 5
          path: |
            "portable\MTApiService.dll"
            "portable\MQL5\Libraries\MTApiService.dll"
            "portable\MQL5\Libraries\MT5Connector.lib"
            "portable\MQL5\Libraries\MT5Connector.exp"
            "portable\MQL5\Experts\MtApi5.ex5"
            "portable\MQL5\Experts\MtApi5.mq5"
            "portable\MQL5\Include\hash.mqh"
            "portable\MQL5\Include\json.mqh"
            "client\MtApi5.dll"
            "client\MtApiServiceNetCore.dll"
            "MtApi5Installer_x86.msi"
      - name: Latest
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: Latest
          files: |
            "portable\MTApiService.dll"
            "portable\MQL5\Libraries\MTApiService.dll"
            "portable\MQL5\Libraries\MT5Connector.lib"
            "portable\MQL5\Libraries\MT5Connector.exp"
            "portable\MQL5\Experts\MtApi5.ex5"
            "portable\MQL5\Experts\MtApi5.mq5"
            "portable\MQL5\Include\hash.mqh"
            "portable\MQL5\Include\json.mqh"
            "client\MtApi5.dll"
            "client\MtApiServiceNetCore.dll"
            "MtApi5Installer_x86.msi"
