name: GitHub Actions Build
run-name: Building & uploading projects
on: [push]
jobs:
  Build-Solution:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '5.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore nuget packages
        run: nuget restore MetaTraderApi_2017.sln
      - run: echo "🖥️ The workflow will now start building the MTApiService.dll"
      - name: Build MTApiService for release
        run: msbuild MTApiService\MTApiService.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Build MtApi5 for release
        run: dotnet build MtApi5\MtApi5.csproj -c Release
      - name: Build MT5Connector for release
        run: msbuild MT5Connector\MT5Connector.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release        
      - name: Build Installer for release
        run: msbuild MtApi5Installer\MtApi5Installer.wixproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Prepair target file structure
        env:
          WORK_DIR: ${{ github.workspace }}
          BUILD_DIR: ${{ github.workspace }}\build\products\Release 
        run: |
          mkdir ${{ env.WORK_DIR }}\portable
          mkdir ${{ env.WORK_DIR }}\portable\MQL5
          mkdir ${{ env.WORK_DIR }}\portable\MQL5\Experts
          mkdir ${{ env.WORK_DIR }}\portable\MQL5\Include
          mkdir ${{ env.WORK_DIR }}\client
          move "${{ env.BUILD_DIR }}\MTApiService.dll" "${{ env.WORK_DIR }}\portable\MTApiService.dll"
          move "${BUILD_DIR}\MT5Connector.dll" "${WORK_DIR}\portable\MQL5\Libraries\MTApiService.dll"
          move "${BUILD_DIR}\MT5Connector.lib" "${WORK_DIR}\portable\MQL5\Libraries\MT5Connector.lib"
          move "${BUILD_DIR}\MT5Connector.exp" "${WORK_DIR}\portable\MQL5\Libraries\MT5Connector.exp"
          move "${WORK_DIR}\mq5\MtApi5.ex5" "${WORK_DIR}\portable\MQL5\Experts\MtApi5.ex5"
          move "${WORK_DIR}\mq5\MtApi5.mq5" "${WORK_DIR}\portable\MQL5\Experts\MtApi5.mq5"
          move "${WORK_DIR}\mq5\hash.mqh" "${WORK_DIR}\portable\MQL5\Include\hash.mqh"
          move "${WORK_DIR}\mq5\json.mqh" "${WORK_DIR}\portable\MQL5\Include\json.mqh"
          move "${BUILD_DIR}\MtApi5.dll" "${WORK_DIR}\client\MtApi5.dll"
          move "${BUILD_DIR}\MtApiServiceNetCore.dll" "${WORK_DIR}\client\MtApiServiceNetCore.dll"
          move "${BUILD_DIR}\MtApi5Installer_x86.msi" "${WORK_DIR}\MtApi5Installer_x86.msi"
      - name: PR artifacts
        uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/master'
        with:
          name: MetaTraderApi
          retention-days: 5
          path: |
            "portable\MTApiService.dll"
            "portable\MQL5\Libraries\MTApiService.dll"
            "portable\MQL5\Libraries\MT5Connector.lib"
            "portable\MQL5\Libraries\MT5Connector.exp"
            "portable\MQL5\Experts\MtApi5.ex5"
            "portable\MQL5\Experts\MtApi5.mq5"
            "portable\MQL5\Include\hash.mqh"
            "portable\MQL5\Include\json.mqh"
            "client\MtApi5.dll"
            "client\MtApiServiceNetCore.dll"
            "MtApi5Installer_x86.msi"
      - name: Latest
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: Latest
          files: |
            "portable\MTApiService.dll"
            "portable\MQL5\Libraries\MTApiService.dll"
            "portable\MQL5\Libraries\MT5Connector.lib"
            "portable\MQL5\Libraries\MT5Connector.exp"
            "portable\MQL5\Experts\MtApi5.ex5"
            "portable\MQL5\Experts\MtApi5.mq5"
            "portable\MQL5\Include\hash.mqh"
            "portable\MQL5\Include\json.mqh"
            "client\MtApi5.dll"
            "client\MtApiServiceNetCore.dll"
            "MtApi5Installer_x86.msi"
